### ISSUE TITLE
System tenant's DNS pod stuck in Pending state on one of RPs at 2X2 scale-out environment

### ISSUE THREAD

**Issue by q131172019** [CentaurusInfra/arktos#1202] opened 2021-09-28 17:31 UTC
**What happened**:
When 2X2 scale-out environment is up, system tenant's DNS pod stuck in Pending state.
```
NAMESPACE     NAME                                                   HASHKEY               READY   STATUS    RESTARTS   AGE   IP            NODE               NOMINATED NODE   READINESS GATES
kube-system   pod/coredns-default-ip-172-31-3-192-69bfb6dcdd-gngcm   7669187634640235328   1/1     Running   0          58m   10.245.0.19   ip-172-31-13-237   <none>           <none>
kube-system   pod/kube-dns-554c5866fc-twwwb                          6460076342526896971   0/3     Pending   0          58m   <none>        ip-172-31-5-191    <none>           <none>
```

**What you expected to happen**:
When 2X2 scale-out environment is up, system tenant's DNS pod should be in Running state.

**How to reproduce it (as minimally and precisely as possible)**:
Use script ./hack/arktos-up-scale-out-poc.sh to start 2 X 2 scale-out environment.

**Anything else we need to know?**:
When 2X2 scale-out environment is up, system tenant's DNS pod may be in Running state, may be in Pending state.

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by h-w-chen** [comment] 2022-01-24 20:27
this defect was root caused by configmap/sa of (system tenant) pods cannot be fetched properly by kubelet , since kubelet cannot track back to the proper TP source in that case. This should have been fixed by PR #1244.

**Closed by h-w-chen** 2022-01-24 20:27 UTC
