### ISSUE TITLE
Cannot create pod using modified containerd

### ISSUE THREAD

**Issue by clu2xlu** [CentaurusInfra/arktos#1043] opened 2021-03-22 20:28 UTC
**What happened**:
In order to integrate arktos with mizar, we need customized containerd for Arktos which can pass K8S_POD_TENANT and cni-args annotations to cni plugin as CNI_ARGS parameter.
https://github.com/CentaurusInfra/containerd/commit/e594285944a0f319a82cda00556553e7100085ac

To apply customized containerd, we did: 
1.	switch to root, and cd to arktos folder
2.	./hack/setup-dev-node.sh
3.     following instruction https://github.com/CentaurusInfra/containerd/releases/tag/tenant-cni-args
4.     export CONTAINER_RUNTIME_ENDPOINT="containerRuntime,container,/run/containerd/containerd.sock"
5.     ./hack/arktos-up.sh
6.    ./cluster/kubectl.sh run pod1 --image=nginx

The pod failed to create

NAME                   HASHKEY               READY   STATUS              RESTARTS   AGE
pod1-84bcbcd8b-4h26j   1987100539178716644   0/1     ContainerCreating   0          6m48s

from kubelet.log
````
E0322 20:17:15.708583   36621 remote_runtime.go:107] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to create containerd task: dial unix ^@/run/containerd/s/f4230ffd3d8b8352ddc19bf83a345e20ee7181df01950cb0b3f7cfd72d998854: connect: connection refused: unknown
E0322 20:17:15.708641   36621 kuberuntime_sandbox.go:86] CreatePodSandbox for pod "pod1-84bcbcd8b-p9vmq_default_system(85b69ee5-2f32-404a-a72b-8c784224e9e8)" failed: rpc error: code = Unknown desc = failed to create containerd task: dial unix ^@/run/containerd/s/f4230ffd3d8b8352ddc19bf83a345e20ee7181df01950cb0b3f7cfd72d998854: connect: connection refused: unknown
E0322 20:17:15.708665   36621 kuberuntime_manager.go:1024] createPodSandbox for pod "pod1-84bcbcd8b-p9vmq_default_system(85b69ee5-2f32-404a-a72b-8c784224e9e8)" failed: rpc error: code = Unknown desc = failed to create containerd task: dial unix ^@/run/containerd/s/f4230ffd3d8b8352ddc19bf83a345e20ee7181df01950cb0b3f7cfd72d998854: connect: connection refused: unknown
E0322 20:17:15.708756   36621 pod_workers.go:196] Error syncing pod 85b69ee5-2f32-404a-a72b-8c784224e9e8 ("pod1-84bcbcd8b-p9vmq_default_system(85b69ee5-2f32-404a-a72b-8c784224e9e8)"), skipping: failed to "CreatePodSandbox" for "pod1-84bcbcd8b-p9vmq_default_system(85b69ee5-2f32-404a-a72b-8c784224e9e8)" with CreatePodSandboxError: "CreatePodSandbox for pod \"pod1-84bcbcd8b-p9vmq_default_system(85b69ee5-2f32-404a-a72b-8c784224e9e8)\" failed: rpc error: code = Unknown desc = failed to create containerd task: dial unix \x00/run/containerd/s/f4230ffd3d8b8352ddc19bf83a345e20ee7181df01950cb0b3f7cfd72d998854: connect: connection refused: unknown"
````

**What you expected to happen**:
We should be able to deploy mizar operator pods and daemon pods, but we couldn't deploy any pods 

**How to reproduce it (as minimally and precisely as possible)**:
1.	switch to root, and cd to arktos folder
2.	./hack/setup-dev-node.sh
3.     following instruction https://github.com/CentaurusInfra/containerd/releases/tag/tenant-cni-args
4.     export CONTAINER_RUNTIME_ENDPOINT="containerRuntime,container,/run/containerd/containerd.sock"
5.     ./hack/arktos-up.sh
6.    ./cluster/kubectl.sh run pod1 --image=nginx

**Anything else we need to know?**:

We tried roll back to our previous commit https://github.com/CentaurusInfra/arktos/commit/664370e83b637ffb7247811fbc58b7087dadc948
where we had mizar and arktos working in Sep 2020
Unfortunately, when I tried to deploy customized containerd with this commit back in Sep 2020, I was not able to deploy any pod. 
See comments below for more detailed logs. 

**Environment**:
- Arktos version (use `kubectl version`): latest
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.3 LTS
- Kernel (e.g. `uname -a`): 5.6.0-rc2 #1 SMP x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
- Network plugin and version (if this is a network-related bug): 
- containerd: https://github.com/CentaurusInfra/containerd/commit/e594285944a0f319a82cda00556553e7100085ac

**Comment by clu2xlu** [comment] 2021-03-22 20:50
Using Commit from Sep 2020, https://github.com/CentaurusInfra/arktos/commit/664370e83b637ffb7247811fbc58b7087dadc948
we got: 

cd /home/ubuntu/go/src/k8s.io/arktos
./hack/setup-dev-node.sh
wget -qO- https://github.com/futurewei-cloud/containerd/releases/download/tenant-cni-args/containerd.zip | zcat > /tmp/containerd
chmod +x /tmp/containerd
sudo systemctl stop containerd
sudo mv /usr/bin/containerd /usr/bin/containerd.bak
sudo mv /tmp/containerd /usr/bin/
sudo systemctl restart containerd
sudo systemctl start docker
export CONTAINER_RUNTIME_ENDPOINT="containerRuntime,container,/run/containerd/containerd.sock"
sudo systemctl status containerd


❯ sudo systemctl status containerd
```
● containerd.service - containerd container runtime
   Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-03-19 23:48:05 UTC; 27s ago
     Docs: https://containerd.io
  Process: 4766 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
 Main PID: 4767 (containerd)
    Tasks: 24
   CGroup: /system.slice/containerd.service
           ├─3590 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/8d9699e72ea162527ead0b1823f593e200d54a2d7cb31d5b22db938f31465081
           ├─3608 registry serve /etc/docker/registry/config.yml
           └─4767 /usr/bin/containerd

Mar 19 23:48:05 ip-172-31-28-87 containerd[4767]: time="2021-03-19T23:48:05.286183063Z" level=info msg="loading plugin \"io.containerd.grpc.v1.introspection\"..." type=io.containe
Mar 19 23:48:05 ip-172-31-28-87 containerd[4767]: time="2021-03-19T23:48:05.286873649Z" level=info msg="Start subscribing containerd event"
Mar 19 23:48:05 ip-172-31-28-87 containerd[4767]: time="2021-03-19T23:48:05.286880709Z" level=info msg=serving... address=/run/containerd/containerd.sock.ttrpc
Mar 19 23:48:05 ip-172-31-28-87 containerd[4767]: time="2021-03-19T23:48:05.287019282Z" level=info msg="Start recovering state"
Mar 19 23:48:05 ip-172-31-28-87 containerd[4767]: time="2021-03-19T23:48:05.287401454Z" level=info msg="Start event monitor"
Mar 19 23:48:05 ip-172-31-28-87 containerd[4767]: time="2021-03-19T23:48:05.287419812Z" level=info msg="Start snapshots syncer"
Mar 19 23:48:05 ip-172-31-28-87 containerd[4767]: time="2021-03-19T23:48:05.287431238Z" level=info msg="Start cni network conf syncer"
Mar 19 23:48:05 ip-172-31-28-87 containerd[4767]: time="2021-03-19T23:48:05.287438915Z" level=info msg="Start streaming server"
Mar 19 23:48:05 ip-172-31-28-87 containerd[4767]: time="2021-03-19T23:48:05.287326576Z" level=info msg=serving... address=/run/containerd/containerd.sock
Mar 19 23:48:05 ip-172-31-28-87 containerd[4767]: time="2021-03-19T23:48:05.287564877Z" level=info msg="containerd successfully booted in 0.037469s"
```

cd /home/ubuntu/go/src/k8s.io/arktos
export PATH=$PATH:/usr/local/go/bin
source $HOME/.profile
./hack/arktos-up.sh

systemctl status containerd
```
containerd.service - containerd container runtime
   Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-03-19 23:48:05 UTC; 17min ago
     Docs: https://containerd.io
 Main PID: 4767 (containerd)
    Tasks: 41
   CGroup: /system.slice/containerd.service
           ├─  998 /usr/bin/containerd-shim-runc-v1 -namespace k8s.io -id a73987dbb350f66ba0443dc2b0d0ef2ea3ceadd0653ff285ab11c97abe4fc9a9 -address /run/containerd/containerd.sock
           ├─ 3590 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/8d9699e72ea162527ead0b1823f593e200d54a2d7cb31d5b22db938f3146508
           ├─ 3608 registry serve /etc/docker/registry/config.yml
           ├─ 4767 /usr/bin/containerd
           ├─15297 /opt/cni/bin/bridge
           └─15318 /sbin/iptables -t nat -S --wait

Mar 20 00:05:09 ip-172-31-28-87 containerd[4767]: time="2021-03-20T00:05:09.116134522Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:kube-dns-6fdcc959b4-ht9m6,Uid:21
Mar 20 00:05:10 ip-172-31-28-87 containerd[4767]: time="2021-03-20T00:05:10.642382296Z" level=error msg="copy shim log" error="reading from a closed fifo"
Mar 20 00:05:11 ip-172-31-28-87 containerd[4767]: time="2021-03-20T00:05:11.420717494Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:kube-dns-6fdcc959b4-ht9m6,Uid:2
Mar 20 00:05:17 ip-172-31-28-87 containerd[4767]: time="2021-03-20T00:05:17.116640475Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:virtlet-tzgfd,Uid:a62c44f9-8bbb-
Mar 20 00:05:17 ip-172-31-28-87 containerd[4767]: time="2021-03-20T00:05:17.131707538Z" level=error msg="copy shim log" error="reading from a closed fifo"
Mar 20 00:05:17 ip-172-31-28-87 containerd[4767]: time="2021-03-20T00:05:17.136733038Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:virtlet-tzgfd,Uid:a62c44f9-8bbb
Mar 20 00:05:19 ip-172-31-28-87 containerd[4767]: time="2021-03-20T00:05:19.116359849Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:pod1-84bcbcd8b-4h26j,Uid:67e4706
Mar 20 00:05:20 ip-172-31-28-87 containerd[4767]: time="2021-03-20T00:05:20.442021019Z" level=error msg="copy shim log" error="reading from a closed fifo"
Mar 20 00:05:21 ip-172-31-28-87 containerd[4767]: time="2021-03-20T00:05:21.246794658Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:pod1-84bcbcd8b-4h26j,Uid:67e470
Mar 20 00:05:24 ip-172-31-28-87 containerd[4767]: time="2021-03-20T00:05:24.116614940Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:kube-dns-6fdcc959b4-ht9m6,Uid:21
lines 1-24/24 (END)
```

alias kubectl='/home/ubuntu/go/src/k8s.io/arktos/cluster/kubectl.sh'
docker pull nginx
kubectl run pod1 --image=nginx
kubectl get pods

NAME                   HASHKEY               READY   STATUS              RESTARTS   AGE
pod1-84bcbcd8b-4h26j   1987100539178716644   0/1     ContainerCreating   0          6m48s

❯ ls /etc/cni/net.d
bridge.conf

vim /tmp/kubelet.log
```
E0319 23:56:23.495262   31292 pod_workers.go:196] Error syncing pod 67e47069-c9da-43d4-aa31-62e601935778 ("pod1-84bcbcd8b-4h26j_default_system(67e47069-c9da-43d4-aa31-62e601935778
)"), skipping: failed to "CreatePodSandbox" for "pod1-84bcbcd8b-4h26j_default_system(67e47069-c9da-43d4-aa31-62e601935778)" with CreatePodSandboxError: "CreatePodSandbox for pod \
"pod1-84bcbcd8b-4h26j_default_system(67e47069-c9da-43d4-aa31-62e601935778)\" failed: rpc error: code = Unknown desc = failed to create containerd task: dial unix \x00/run/containe
rd/s/c950a3f1fe0eec86e3e2309fed2e8c85672a9d5cf5955aab57a15060ac57fdbe: connect: connection refused: unknown"
```

**Comment by clu2xlu** [comment] 2021-03-22 21:15
Latest Commit: 

   sudo su
  cd /home/ubuntu/go/src/k8s.io/arktos
  ./hack/setup-dev-node.sh
  wget -qO- https://github.com/futurewei-cloud/containerd/releases/download/tenant-cni-args/containerd.zip | zcat > /tmp/containerd
 chmod +x /tmp/containerd
 sudo systemctl stop containerd
 sudo mv /usr/bin/containerd /usr/bin/containerd.bak
 sudo mv /tmp/containerd /usr/bin/
 sudo systemctl restart containerd
 sudo systemctl start docker
 export CONTAINER_RUNTIME_ENDPOINT="containerRuntime,container,/run/containerd/containerd.sock"

❯ sudo systemctl status containerd
```
● containerd.service - containerd container runtime
   Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-03-22 20:57:18 UTC; 1min 42s ago
     Docs: https://containerd.io
  Process: 10827 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
 Main PID: 10828 (containerd)
    Tasks: 45
   CGroup: /system.slice/containerd.service
           ├─ 3613 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/661d3a5e42589e006141569046b6b1b996765e1f1ae1cb8082dc466bb510fa4
           ├─ 3614 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/455381eab4ea58ac30dac55f082a526c7218bd58bbfa7b1731fd7bd3dc6d671
           ├─ 3822 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/8d9699e72ea162527ead0b1823f593e200d54a2d7cb31d5b22db938f3146508
           ├─ 3841 registry serve /etc/docker/registry/config.yml
           └─10828 /usr/bin/containerd

Mar 22 20:57:18 ip-172-31-21-122 containerd[10828]: time="2021-03-22T20:57:18.946493430Z" level=info msg="loading plugin \"io.containerd.grpc.v1.introspection\"..." type=io.contai
Mar 22 20:57:18 ip-172-31-21-122 containerd[10828]: time="2021-03-22T20:57:18.946680796Z" level=info msg="Start subscribing containerd event"
Mar 22 20:57:18 ip-172-31-21-122 containerd[10828]: time="2021-03-22T20:57:18.946725870Z" level=info msg=serving... address=/run/containerd/containerd.sock.ttrpc
Mar 22 20:57:18 ip-172-31-21-122 containerd[10828]: time="2021-03-22T20:57:18.946752542Z" level=info msg="Start recovering state"
Mar 22 20:57:18 ip-172-31-21-122 containerd[10828]: time="2021-03-22T20:57:18.946774581Z" level=info msg=serving... address=/run/containerd/containerd.sock
Mar 22 20:57:18 ip-172-31-21-122 containerd[10828]: time="2021-03-22T20:57:18.946794166Z" level=info msg="containerd successfully booted in 0.041441s"
Mar 22 20:57:18 ip-172-31-21-122 containerd[10828]: time="2021-03-22T20:57:18.975458995Z" level=info msg="Start event monitor"
Mar 22 20:57:18 ip-172-31-21-122 containerd[10828]: time="2021-03-22T20:57:18.975509643Z" level=info msg="Start snapshots syncer"
Mar 22 20:57:18 ip-172-31-21-122 containerd[10828]: time="2021-03-22T20:57:18.975523629Z" level=info msg="Start cni network conf syncer"
Mar 22 20:57:18 ip-172-31-21-122 containerd[10828]: time="2021-03-22T20:57:18.975531465Z" level=info msg="Start streaming server"
```

./hack/arktos-up.sh

❯ systemctl status containerd
```
● containerd.service - containerd container runtime
   Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-03-22 20:57:18 UTC; 15min ago
     Docs: https://containerd.io
  Process: 10827 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
 Main PID: 10828 (containerd)
    Tasks: 45
   CGroup: /system.slice/containerd.service
           ├─ 3613 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/661d3a5e42589e006141569046b6b1b996765e1f1ae1cb8082dc466bb510fa4
           ├─ 3614 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/455381eab4ea58ac30dac55f082a526c7218bd58bbfa7b1731fd7bd3dc6d671
           ├─ 3822 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/8d9699e72ea162527ead0b1823f593e200d54a2d7cb31d5b22db938f3146508
           ├─ 3841 registry serve /etc/docker/registry/config.yml
           └─10828 /usr/bin/containerd

Mar 22 21:11:59 ip-172-31-21-122 containerd[10828]: time="2021-03-22T21:11:59.000608465Z" level=error msg="copy shim log" error="reading from a closed fifo"
Mar 22 21:11:59 ip-172-31-21-122 containerd[10828]: time="2021-03-22T21:11:59.004371244Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:virtlet-74v9t,Uid:0cccec2a-84
Mar 22 21:11:59 ip-172-31-21-122 containerd[10828]: time="2021-03-22T21:11:59.380307418Z" level=error msg="copy shim log" error="reading from a closed fifo"
Mar 22 21:12:00 ip-172-31-21-122 containerd[10828]: time="2021-03-22T21:12:00.920276954Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:kube-dns-6fdcc959b4-qrts8,Uid
Mar 22 21:12:13 ip-172-31-21-122 containerd[10828]: time="2021-03-22T21:12:13.982171915Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:virtlet-74v9t,Uid:0cccec2a-848
Mar 22 21:12:13 ip-172-31-21-122 containerd[10828]: time="2021-03-22T21:12:13.997593669Z" level=error msg="copy shim log" error="reading from a closed fifo"
Mar 22 21:12:14 ip-172-31-21-122 containerd[10828]: time="2021-03-22T21:12:14.001439797Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:virtlet-74v9t,Uid:0cccec2a-84
Mar 22 21:12:14 ip-172-31-21-122 containerd[10828]: time="2021-03-22T21:12:14.982035440Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:kube-dns-6fdcc959b4-qrts8,Uid:
Mar 22 21:12:16 ip-172-31-21-122 containerd[10828]: time="2021-03-22T21:12:16.376164876Z" level=error msg="copy shim log" error="reading from a closed fifo"
Mar 22 21:12:17 ip-172-31-21-122 containerd[10828]: time="2021-03-22T21:12:17.244253691Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:kube-dns-6fdcc959b4-qrts8,Uid
lines 1-24/24 (END)
```
alias kubectl='/home/ubuntu/go/src/k8s.io/arktos/cluster/kubectl.sh'
docker pull nginx
kubectl run pod1 --image=nginx
❯ kubectl get pods
```
NAME                   HASHKEY               READY   STATUS              RESTARTS   AGE
pod1-84bcbcd8b-shdqf   3342600586929671369   0/1     ContainerCreating   0          6s
```

vim /tmp/kubelet.log
```
E0322 21:13:35.212742   42065 kuberuntime_manager.go:1024] createPodSandbox for pod "pod1-84bcbcd8b-shdqf_default_system(fa55f7e5-01f2-4caf-a47d-6cf285baa687)" failed: rpc error: code = Unknown desc = failed to create containerd task: dial unix ^@/run/containerd/s/95d3be04a48f39373bb57adacec21ed0443f65e582cacee92485c1d398ce5968: connect: connection refused: unknown
E0322 21:13:35.212829   42065 pod_workers.go:196] Error syncing pod fa55f7e5-01f2-4caf-a47d-6cf285baa687 ("pod1-84bcbcd8b-shdqf_default_system(fa55f7e5-01f2-4caf-a47d-6cf285baa687)"), skipping: failed to "CreatePodSandbox" for "pod1-84bcbcd8b-shdqf_default_system(fa55f7e5-01f2-4caf-a47d-6cf285baa687)" with CreatePodSandboxError: "CreatePodSandbox for pod \"pod1-84bcbcd8b-shdqf_default_system(fa55f7e5-01f2-4caf-a47d-6cf285baa687)\" failed: rpc error: code = Unknown desc = failed to create containerd task: dial unix \x00/run/containerd/s/95d3be04a48f39373bb57adacec21ed0443f65e582cacee92485c1d398ce5968: connect: connection refused: unknown"
```

**Comment by h-w-chen** [comment] 2021-03-23 04:06
reproduced on local env (Ubuntu 20.04.1 LTS)
arktos master branch latest commit 8e5c308a2a1da21e18a8949db7224d16fba01f08

**Comment by h-w-chen** [comment] 2021-03-23 05:48
turns out the containerd 1.3.3 (used in Ubuntu apt repo) is not compatible with the modified containerd which is on top of 1.4.0-beta1.

Incompatibility was resolved as: 
* upgraded containerd to [1.4.2](https://github.com/containerd/containerd/releases/download/v1.4.2/containerd-1.4.2-linux-amd64.tar.gz)
* and replaced with the modified containerd as [instructed](https://github.com/CentaurusInfra/containerd/releases/tag/tenant-cni-args).

The customized containerd release note was updated to include the confirmed-to-work version.

**Comment by h-w-chen** [comment] 2021-03-23 20:58
Cathy confirmed that issue was gone with the resolution. closed it for now.

**Closed by h-w-chen** 2021-03-23 20:58 UTC
